### PR TITLE
pre-commit hooks

### PR DESCRIPTION
**Pull request by alancleary**
This PR adds pre-commit hooks for [Black](https://black.readthedocs.io/en/stable/index.html), [Flake8](https://flake8.pycqa.org/en/latest/), and [isort](https://pycqa.github.io/isort/) using the [pre-commit framework](https://pre-commit.com/). The hooks were applied to the existing code (thus all the changes). I also added a `.github/CONTRIBUTING.md` file that describes how to setup and use the pre-commit hooks, in addition to providing general guidelines on making contributions.

### CODE REVIEW

**Comment by ctcncgr** [comment]
I like this and updated my newer repo at https://github.com/legumeinfo/DSCensor to use the same pre-commit workflow.

**Review by ctcncgr — APPROVED** [review]
Looks good and the pre-commit hooks work for my other repos as well.

**Comment by alancleary** [comment]
Thanks for the review @ctcncgr! What do you think of using [pre-commit.ci](https://pre-commit.ci/) to run the pre-commit hooks on PRs? That way changes made by developers that opted not to install/use the pre-commit hooks will still be subjected to the hooks.

**Comment by alancleary** [comment]
OK. I installed the pre-commit.ci GitHub app for the legumeinfo organization and set it to only run on this repo. I guess we'll see it in action soon enough.

**Pull request merged**
